config/routes.rb
Atbru::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  scope '(:year)' do
    resources :speakers
    resources :sponsors
    resources :sponsoring
    resources :details
    resources :presentations
    resources :registrations
    resource :program, :controller => "Program"
  end

  root :to => 'welcome#index'

end

app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :registration
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  attr_accessor :agree_terms

  has_many :participants, :dependent => :destroy

  accepts_nested_attributes_for :participants
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :days_left
  protect_from_forgery
  before_filter :set_year

  PREVIOUS_YEARS = ["2013"]

  def days_left
    @days_left = (Date.new(2014, 10, 28) - Date.today).to_i
  end

  private
  def set_year
    @year = params[:year] if params[:year] && PREVIOUS_YEARS.include?(params[:year])
  end
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  def index
    render [ @year, 'details', 'index' ].join('/')
  end
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  def index
    render [ @year, 'presentations', 'index' ].join('/')
  end
end

app/controllers/program_controller.rb
class ProgramController < ApplicationController
  def show
    render [ @year, 'program', 'show' ].join('/')
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def index
    @registration = Registration.new
    @registration.participants.build
    @participant_count  = Participant.count
    @progress_bar_value = ((@participant_count / 80.0) * 100).round
  end

  def create
    @participant_count = Participant.count
    @registration      = Registration.new(params[:registration])
    if @registration.save
      RegistrationMailer.registration_created(@registration).deliver
      RegistrationMailer.thanks_registration(@registration).deliver
      flash[:notice] = "We have been notified of your registration, you should receive an invoice in the following hours. Thank you!"
    else
      flash[:error] = "There was a problem with your registration, please try again later..."
    end
    redirect_to registrations_path
  end
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  def index
    render [ @year, 'speakers', 'index' ].join('/')
  end
end

app/controllers/sponsoring_controller.rb
class SponsoringController < ApplicationController
  def index
    render [ @year, 'sponsoring', 'index' ].join('/')
  end
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  def index
    render [ @year, 'sponsors', 'index' ].join('/')
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/labels_helper.rb
#encoding: UTF-8
module LabelsHelper

  def label type

      title = case type
              when :beginner then 'Beginner friendly'
              else type.to_s
              end
      text =  case type
              # when :beginner then '★☆☆ Beginner'
              when :beginner then '★ Beginner'
              when :practitioner then '★★ Practitioner'
              when :expert then '★★★ Expert'
              else type.to_s
              end
    content_tag :span, class: [ :label, :"label-#{type}" ], title: title do
      text
    end
  end

  def labels *labels
    labels = Array(labels)
    labels.map!{ |l| label l }
    content_tag :div, class: [ :labels ] do
      labels.join('<br />').html_safe
    end
  end
end

app/views/details/index.html.haml
%h1.giant.title Agile Tour Brussels 2014
.large.ribbon Practical details

%section#getting-there
  %br/
  %br/
  %h2 Getting to the EPHEC
  %h3 By train
  %p
    Merode station is at 14 min. distance by underground.
  %h3 By underground
  %p
    Line 1 direction Stockel; Stop Alma at 5 min. walking distance.
  %h3 By car
  %p
    The EPHEC is situated near the “Cliniques Universitaires Saint-Luc”.
  %h3 Parking
  %p If you come by car, a free parking is available (100 spots). There is also a possibility to park in the streets in the proximity.
  %p
    Just go to the EPHEC and watch the EPHEC PARKING -1 and -2.
    You will have to "ring" and tell that you are coming for Agile Tour Brussels.
    %br/
    Note that -2 is the biggest parking.
  %p (We still recommend to use public transportation in Brussels and to avoid using your car if possible).
  %h3 Address
  %p EPHEC Ecole Pratique des Hautes Etudes Commerciales  | Avenue Konrad Adenauer 3 | 1200 Woluwe-Saint-Lambert

#location
  #map


%section#staying
  :markdown
    ## Staying in Brussels
    ### Hotels in close proximity to the EPHEC

    * The closest hotel is [**The Best Western Premier Sodehotel**](http://www.premiersodehotellawoluwe.com/), La Woluwe

    ### Brussels airport hotels (Diegem, Corporate Village)
    * [NH Hotel](http://www.nh-hotels.com/nh/en/hotels/belgium/brussels/nh-brussels-airport.html)
    * [Thon Hotel](http://www.thonhotels.com/hotels/countrys/belgium/brussels/thon-hotel-brussels-airport/)
    * [Novotel](http://www.accorhotels.com/gb/hotel-0467-novotel-brussels-airport/index.shtml)
    * [Crowne Plaza](http://www.ihg.com/crowneplaza/hotels/us/en/brussels/bruzm/hoteldetail)

    ### Public transport from/ to the airport/ Diegem/ Corporate Village
    **Bus company De Lijn** operates bus services to the Brussels underground station **Roodebeek** (lines **359** and **659**).
    * When taking **line 659**, please get off at **SINT-STEVENS-WOLUWE HIPPOKRATES** bus stop.
    * When taking **line 359**, please get off at **WOLUWEDAL** bus stop

    ### Taxis

    There are plenty of taxis available at all major traffic junctions and near public institutions and major hotels. <br />
    Taxis also provide a rapid connection from and to the airport, see [irisnet.be](http://www.irisnet.be) and [biac.be](http://www.biac.be)

app/views/layouts/application.html.haml
!!!
- content_for :submenu do
  - if @year == '2012'
    %ul.edition_2012
      %li= link_to t("menu.speakers"     ), speakers_url(      year: 2012 )
      %li= link_to t("menu.program"      ), program_url(       year: 2012 )
      %li= link_to t("menu.sponsors"     ), sponsors_url(      year: 2012 )
      %li= link_to t("menu.presentations"), presentations_url( year: 2012 )

%html
  %head
    %title AgileTour Brussels
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=AIzaSyDcnubMfFImIRCFaGm8hvIRrfgWvne3Nyo&sensor=false" unless Rails.env == "development"
    = favicon_link_tag "favicon.png", :type => "image/png"
    = csrf_meta_tags
    %meta{ 'og:image' => "http://www.atbru.be/assets/logo.png" }

  %body{ id: "#{action_name}-#{controller_name}" }
    #wrap
      %header#header
        %h1= link_to image_tag("logo.png", :alt => "AgileTour Brussels"), "/"
        %nav#main-menu
          %ul
            %li= link_to t("menu.home"), root_url

            - if false # TEMPORARLY DISABLE THESE MENU ITEMS
              %li= link_to t("menu.speakers"), speakers_url
              %li= link_to t("menu.presentations"), presentations_url
            %li= link_to t("menu.program"), program_url
            %li= link_to t("menu.sponsors"), sponsors_url
            %li= link_to t("menu.details"), details_url
            /%li=# link_to t("menu.presentations"), presentations_url
        #register-box
          - if show_remaining_days_and_register_button = false
            #counter
              %span.days
                = days_left
              = t("register.days_left")
            .button= link_to t("register.register"), "http://register.agilesystems.org/"
      #content

        = render 'shared/tweet_button'
        <br />
        = yield :before_carousel
        = yield :carousel

        #flash
          - if flash[:notice]
            %p.notice
              = flash[:notice]
          - if flash[:error]
            %p.error
              = flash[:error]
        = yield
      .push
    %footer#footer-sponsors
      .wrap
        %h1.giant.title Sponsors
        #img-box
          =link_to image_tag("small_grey_Cegeka logo.png", :alt => "Cegeka"), "http://www.cegeka.com/"
          =link_to image_tag("small_grey_scrum_alliance_logo_2013.png", :alt => "Scrum Alliance"), "http://www.scrumalliance.org"
          =link_to image_tag("small_grey_pyxis_logo.png", :alt => "Pyxis"), "http://pyxis-tech.com/en"
          =link_to image_tag("small_grey_brunosbille.png", :alt => "BrunoSbille.com"), "http://brunosbille.com/?page_id=2079&lang=fr"
          =link_to image_tag("small_grey_LogoWemanity.png", :alt => "Wemanity"), "http://www.wemanity.com/"
          %br
          %br
          =link_to image_tag("medium_grey_agilar_logo.png", :alt => "Agilar"), "http://www.agilar.be/"
          =link_to image_tag("small_grey_oniryx.png", :alt => "Oniryx"), "http://www.oniryx.be/"


    %footer#footer
      .wrap
        .copyright= t("footer.copyright")
        %nav#footer-nav
          %ul
            %li= link_to t("menu.home"), root_url

            - if false # TEMPORARLY DISABLE THESE MENU ITEMS
              %li= link_to t("menu.speakers"), speakers_url

            %li= link_to t("menu.program"), program_url
            %li= link_to t("menu.sponsors"), sponsors_url
            %li= link_to t("menu.details"), details_url
            /%li=# link_to t("menu.presentations"), presentations_url

= render "shared/map"

app/views/shared/_map.html.haml
:javascript
  $("#slideshow").slides({
    play: 3000,
    pause: 1500,
    generateNextPrev: false,
    generatePagination: false,
    effect: 'fade',
    crossfade: true,
    slideSpeed: 750
  });

  var myOptions = {
    center: new google.maps.LatLng(50.8501557, 4.448685),
    zoom: 15,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById("map"), myOptions);
  var contentString = '<div>'+
    'EPHEC Brussels' +
    '<br />'+
    'Avenue Konrad Adenauer 3'+
    '<br />'+
    '1200 Woluwe-Saint-Lambert'+
    '</div>';

  var infowindow = new google.maps.InfoWindow({
    content: contentString
  });

  var marker = new google.maps.Marker({
    position: new google.maps.LatLng(50.8501557, 4.448685),
    map: map,
    title:"EPHEC Brussels"
  });

  infowindow.open(map,marker);
  map.panBy(20, -90);

app/views/shared/_tweet_button.html.erb
<div id="tweet_button">
<a href="https://twitter.com/intent/tweet?button_hashtag=atbru&text=Agile%20Tour%20Brussels%20-%20the%20conference%20for%20happy%20Agilists%2C%2031%20Oct%2C%202014" class="twitter-hashtag-button" data-url="http://www.atbru.be">Tweet #atbru</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
</div>

app/views/sponsoring/index.html.haml
.edition_2014
  %h1.giant.title Agile Tour Brussels 2014
  .large.ribbon Sponsoring
  %br
  %br
  %h1 Sponsor packages Agile Tour Brussels 2014
  %p 
    We offer the following sponsor options:
  %p 
    <strong>Bar sponsor</strong>: 750 + VAT
    %ul
      %li the sponsor pays for drinks after the conference;
      %li the sponsor will get an acknowledgement during the conference;
      %li sponsor is mentioned in the online program and on the program handout;
  %p 
    <strong>Web sponsor</strong>: 1.000 + VAT
    %ul
      %li sponsor logo and URL will be put on the www.atbru.be website and on the conference hand outs;
      %li the sponsor will get an acknowledgement during the conference opening session;
      %li during the conference, sponsor materials will be available at the registration desk;
      %li the sponsor will get 1 free admission to the conference.
  %p 
    Note:
    %ul
      %li the sponsor is responsible for getting the materials in time at the conference;
      %li the conference organizers will give a timely indication of the number of participants to expect.
  %p 
    <strong>Conference sponsor</strong>: 2.000 + VAT
    %ul 
      %li the sponsor can bring a stand; (Contact us at <a href="mailto:sponsoring@atbru.be">sponsoring</a> for a map of the rooms and stands at the venue.)
      %li sponsor logo and URL will be put on the www.atbru.be website and on the conference hand outs;
      %li the sponsor will get an acknowledgement during the conference opening session;
      %li during the conference, sponsor materials will be available at the registration desk;
      %li the sponsor will get 3 free admission to the conference.
  %p 
    Note:
    %ul
      %li the sponsor is responsible for getting the materials in time at the conference;
      %li the sponsor is responsible for the stand;
      %li the conference organizers will give a timely indication of the number of participants to expect.
  %p
    <strong>Agile Tour Brussels + XP Days sponsor</strong>:  30% discount on both packages
  %p
    Why not sponsor both Agile Tour Brussels (1 day, 180 participants) and XP Days in november (2 days, 160 participants)? You get:
    %ul 
      %li Exposure the whole year long
      %li Lower cost than sponsoring each event separately
  %p 
    <strong>Tailored Package</b>
  %p
    Contact us at 
    %a(href="mailto:sponsoring@atbru.be") sponsoring
    for pricing or to create a sponsoring package tailored to your wishes.
  %p 
    <strong>Media sponsoring</strong>
    %ul
      %li a media sponsor mentions the conference (logo, conference name, location, date, URL), on a website and/or in a magazine and/or in a mailing;
      %li sponsor logo and URL will be put on the www.atbru.be website;
      %li the sponsor will get an acknowledgement during the conference opening sessions.

   

app/views/sponsors/index.html.haml
- if false # disabled content
  - content_for :carousel do
    #slideshow
      .slides_container
        %div= image_tag "sponsors.jpg"

.edition_2014
  %h1.giant.title Agile Tour Brussels 2014
  .large.ribbon Sponsors

  %section.sponsor#options
    %br
    %br
    %p
      Want to see your company here? Have a look at our 
      %a(href="./sponsoring.html") Sponsoring options 
      and contact 
      %a(href="mailto:sponsoring@atbru.be") sponsoring 
      to see how we can work together to make Agile Tour 2014 a great day for the participants and your company.
  
  %section#sponsors
    %br
    %br
    :markdown

      ## Gold Sponsors

    .wrap
      #img-box
        =link_to image_tag("medium_color_cegeka_logo.png", :alt => "Cegeka"), "http://www.cegeka.com/"
        =link_to image_tag("medium_color_pyxis_logo.png", :alt => "Pyxis"), "http://pyxis-tech.com/en"
        =link_to image_tag("medium_color_sa_logo.png", :alt => "Scrum Alliance"), "http://www.scrumalliance.org"
        =link_to image_tag("medium_color_wemanity_logo.png", :alt => "Wemanity"), "http://www.wemanity.com/"
        =link_to image_tag("medium_color_brunosbille_logo.png", :alt => "BrunoSbille.com"), "http://brunosbille.com/?page_id=2079&lang=fr"
        %br
        =link_to image_tag("large_color_agilar_logo.png", :alt => "Agilar"), "http://www.agilar.be/"
        =link_to image_tag("medium_color_logo_agile_oniryx.png", :alt => "Oniryx"), "http://www.oniryx.be/"

    %br
    %br
    :markdown

      ## Partners

    .wrap
      #img-box
        =link_to image_tag("medium_color_logo_sabai.png", :alt => "Sabai"), "http://www.sabai-institut.com"
        &nbsp;&nbsp;
        =link_to image_tag("medium_color_logo_ees.jpg", :alt => "Espace en soi"), "http://www.espace-en-soi.org"
        

    %br
    %br
    :markdown

      ## Community sponsors

    .wrap
      #img-box

        =link_to image_tag("medium_color_logo_agile_consortium.png", :alt => "Agile Consortium"), "http://www.agileconsortium.net/category/belgium/", :target => "_blank"
        =link_to image_tag("medium_color_logo_agile_systems.png", :alt => "Agile Systems"), "http://agilesystems.org", :target => "_blank"
        =link_to image_tag("medium_color_logo_journee_agile.png", :alt => "La Journée Agile"), "http://www.journeeagile.be/", :target => "_blank"
        =link_to image_tag("medium_color_stattys_logo.png", :alt => "Stattys"), "http://www.stattys.com", :target => "_blank"
        =link_to image_tag("medium_color_logo_devopsday.png", :alt => "DevOps Days"), "http://devopsdays.org/events/2014-belgium/", :target => "_blank"
        =link_to image_tag("medium_color__logo_xpdays2014.png", :alt => "XP Days 2014"), "http://xpdays.net" , :target => "_blank"
        =link_to image_tag("medium_color_logo_agile_belgium.png", :alt => "Agile Belgium"), "http://www.agilebelgium.org/", :target => "_blank"
        =link_to image_tag("medium_color_logo_handson.io.png", :alt => "Handson.io"), "http://handson.io", :target => "_blank"

    %br/
    %br/

app/views/welcome/index.html.haml
- content_for :carousel do
  #slideshow
    .slides_container
      %div= image_tag "carousel/01.jpg"
      %div= image_tag "carousel/02.jpg"
      %div= image_tag "carousel/03.jpg"
      %div= image_tag "carousel/04.jpg"
      %div= image_tag "carousel/05.jpg"
      %div= image_tag "carousel/06.jpg"
      %div= image_tag "carousel/07.jpg"
      %div= image_tag "carousel/08.jpg"
      %div= image_tag "carousel/09.jpg"
      %div= image_tag "carousel/10.jpg"
      %div= image_tag "carousel/11.jpg"
      %div= image_tag "carousel/12.jpg"
      %div= image_tag "carousel/13.jpg"
      %div= image_tag "carousel/14.jpg"
      %div= image_tag "carousel/15.jpg"



- content_for :before_carousel do


  %h1.giant.title
    %big
      Agile Tour Brussels 2014
  .large.ribbon October, 31 at EPHEC Brussels
  %br/
  %br/

  %section#call

    %h1.giant.title
      = link_to image_tag("banner_atbru.png", :alt => "Register"), "http://register.agilesystems.org/"
    %br
    %br
    %section#sponsors.side_content
      %h3 Gold sponsors
      %p
        =link_to image_tag("small_color_Cegeka logo.png", :alt => "Cegeka"), "http://www.cegeka.com/"
        =link_to image_tag("small_color_scrum_alliance_logo_2013.png", :alt => "Scrum Alliance"), "http://www.scrumalliance.org"
      %p
        =link_to image_tag("small_color_pyxis_logo.png", :alt => "Pyxis"), "http://pyxis-tech.com/en"
        =link_to image_tag("small_color_LogoWemanity.png", :alt => "Wemanity"), "http://www.wemanity.com/"
      %p.center
        =link_to image_tag("small_color_brunosbille.png", :alt => "BrunoSbille.com"), "http://brunosbille.com/?page_id=2079&lang=fr"
      %p.center
        =link_to image_tag("medium_color_agilar_logo.jpg", :alt => "Agilar"), "http://www.agilar.be/"
      %p.center 
        =link_to image_tag("small_color_oniryx.png", :alt => "Oniryx"), "http://www.oniryx.be/"

    :markdown
      ### Agile Tour Brussels 2014 - Registration will close Tuesday 28/10/2014

      Hurry up! Time flies and the registration will close Tuseday 28/10/2014 at 17:00

    %br
    %br
    %br
      

    :markdown
      ### Agile Tour Brussels 2014 Program is out!

      Six tracks, 31 talks, games and workshops, speakers from all over Europe and a lot of great content.

      Whether you are an experienced agile practitioner, or just started diving into the Agile sea, do not miss the chance to have a great day learning and sharing your experiences with other Agile enthusiasts.

      The **Early bird registration is open until September 5th**, you can grab your ticket and get a 30% discount on the full price so hurry up!

    %br
    %br
    %br
    :markdown
      ### What's Agile Tour Brussels?

      Agile Tour Brussels ([http://www.atbru.be](http://www.atbru.be)) is one of the biggest agile conferences in Belgium. Last year we gathered 180 attendees and speakers from Belgium, France, U.S, U.K, Luxemburg, Netherlands and Sweden to share our passion for Agile. The purpose of this conference is to gather in one place Agile practitioners and people wanting to know more about Agile.
      At Agile Tour Brussels you will meet a mix of attendees who are either completely **new** to Agile, experienced or **experts**

      If you have any questions, feel free to drop an email at [bruno@atbru.be](mailto:bruno@atbru.be)
      If you cannot make it, you can still support us by tweeting about #atbru, blogging, speaking about our event.

      Thanks in advance for your support!

      The Agile Tour Brussels Organization Team.
  %section#team
    %h1.giant.title Meet the crew
    .member-info
      =image_tag("alanhortz.jpg", :alt => "Alan Hortz")
      %ul
        %li
          %a(href="http://be.linkedin.com/in/alanhortz") Alan Hortz
        %li
          %a(href="https://twitter.com/alanhortz") @alanhortz
    .member-info
      =image_tag("brunosbille.png", :alt => "Bruno Sbille")
      %ul
        %li
          %a(href="http://www.brunosbille.com") Bruno Sbille
        %li
          %a(href="https://twitter.com/brunosbille") @brunosbille
    .member-info
      =image_tag("mauriziopedriale.jpg", :alt => "Maurizio Pedriale")
      %ul
        %li
          %a(href="http://be.linkedin.com/in/mpedriale") Maurizio Pedriale
        %li
          %a(href="https://twitter.com/mpedriale") @mpedriale
    .member-info
      =image_tag("olgasmirnova.jpg", :alt => "Olga Smirnova")
      %ul
        %li
          %a(href="https://www.linkedin.com/pub/olga-smirnova/46/2a6/722") Olga Smirnova
        %li
          %a(href="https://twitter.com/olgabohen") @OlgaBohen
    .member-info
      =image_tag("francoisfrancart.jpg", :alt => "François Francart")
      %ul
        %li
          %a(href="http://www.francart.info") François Francart
        %li
          %a(href="https://twitter.com/ffrancart") @ffrancart
    .member-info
      =image_tag("danielreszka.jpg", :alt => "Daniel Reszka")
      %ul
        %li
          %a(href="http://www.about.me/daniel.r") Daniel Reszka
        %li
          %a(href="https://twitter.com/pixarea") @pixarea
    .member-info
      =image_tag("leandrodoctors.jpg", :alt => "Leandro Doctors")
      %ul
        %li
          %a(href="https://www.linkedin.com/in/leandrodoctors") Leandro Doctors
        %li
          &nbsp;

  #flash
    %p